spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zerofake_product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: UTC

server:
  port: 8082

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html