spring:
  application:
    name: fraud-detection-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zerofake_fraud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
product:
  service:
    url: http://localhost:8082

blockchain:
  service:
    url: http://localhost:8083