spring:
  application:
    name: blockchain-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zerofake_blockchain
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

fabric:
  msp-id: Org1MSP
  channel-name: mychannel
  chaincode-name: zerofake
  crypto-path: \\wsl$\Ubuntu\home\rishi_dargad18\hyperledger\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com

  cert-path: \\wsl$\Ubuntu\home\rishi_dargad18\hyperledger\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\users\User1@org1.example.com\msp\signcerts\cert.pem

  key-directory-path: \\wsl$\Ubuntu\home\rishi_dargad18\hyperledger\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\users\User1@org1.example.com\msp\keystore

  tls-cert-path: \\wsl$\Ubuntu\home\rishi_dargad18\hyperledger\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\peers\peer0.org1.example.com\tls\ca.crt
  peer-endpoint: dns:///localhost:7051
  peer-host-alias: peer0.org1.example.com